### ISSUE TITLE
Incompatibility with AllTheBases

### ISSUE THREAD

**Issue by SaltSouls** [Goldenrevolver/ValheimSpearModsAndFriends#2]
Getting a lot of errors with Azumatts [AllTheBases](https://valheim.thunderstore.io/package/Azumatt/AllTheBases/) and ProperSpears installed. Seems to be a object instancing issue.

### Versions:
Valheim: 217.25
ProperSpears: 1.0.0

### Logs:
[Mod List](https://github.com/Goldenrevolver/ValheimSpearModsAndFriends/files/13062146/mod_list.txt)
[Errors Only](https://github.com/Goldenrevolver/ValheimSpearModsAndFriends/files/13062147/errors.txt)
[Full Log](https://github.com/Goldenrevolver/ValheimSpearModsAndFriends/files/13062149/LogOutput.log)

**Comment by Goldenrevolver** [comment]
looks like Azu forgot a null check in his patch. I'll let him know

**Comment by AzumattDev** [comment]
It's added/updated.
