### ISSUE TITLE
Proper Spears causing Harpoon to not be throwable

### ISSUE THREAD

**Issue by yeldarb420** [Goldenrevolver/ValheimSpearModsAndFriends#5]
Running an up to date server (ashlands)
Installed Proper Spears, Loyal Spears & Harpoon Melee

Everything works & looks great with the exception of not being to throw the harpoon via the mouse-3/middle click, instead it just does the melee attack.
Disabling Proper Spears makes it work.

I love the change Proper Spears + Harpoon Melee brings. Any chance this is an easy fix?
Thanks!

**Comment by Goldenrevolver** [comment]
the mods were made to work with each other and the harpoon works when you only have those mods installed. it's more likely that you have another mod that conflicts with my mods. can you send me your mod list by sending me a log file please
